services:
  - type: web
    name: hamdard-library
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hamdard_library.wsgi:application"
    autoDeploy: true
